/**
 * UI Baseline V1 预览假数据。
 * 全部人名/项目/路径/账号均为虚构；账号身份一律脱敏；不含任何凭据形态数据。
 * 时间基准固定为 FIXED_NOW，保证截图与测试可复现。
 */
import type {
  AccountProfileVM,
  ApprovalVM,
  ArtifactVM,
  ConversationItemVM,
  IssueVM,
  ModelDescriptorVM,
  ProjectVM,
  ProviderProfileVM,
  QuotaVM,
  ResultVM,
  RoleCharterVM,
  RolePlanInput,
  RoleVM,
  RunVM,
  SpaceReconfigurationPreviewVM,
  SpaceVM,
  TaskVM,
  WorkspaceVM,
} from '../client-contract/c1r1p1/generated.ts';

/** 2026-09-09T13:30:00+08:00 */
export const FIXED_NOW = 1788931800000;
const M = 60000;
const H = 3600000;

export const projects: ProjectVM[] = [
  {
    id: 'proj_atlas',
    name: '支付中台重构',
    status: 'ACTIVE',
    hostLabel: 'SSH · core-prod-01',
    displayRoot: '~/work/pay-core',
    spacesCount: 2,
    activeRunsCount: 2,
    issuesCount: 1,
    revision: 41,
  },
  {
    id: 'proj_nova',
    name: '官网改版',
    status: 'ACTIVE',
    hostLabel: 'Local · 本机',
    displayRoot: 'D:\\sites\\nova-web',
    spacesCount: 1,
    activeRunsCount: 0,
    issuesCount: 0,
    revision: 12,
  },
];

export const spaces: SpaceVM[] = [
  {
    id: 'sp_core',
    projectId: 'proj_atlas',
    name: '核心链路组',
    status: 'ACTIVE',
    rolesCount: 3,
    queuedTasksCount: 0,
    revision: 18,
    purpose: '支付核心链路的规划、实现与复核',
    policyRevision: 3,
    activeRunsCount: 2,
    needsUserCount: 1,
  },
  {
    id: 'sp_growth',
    projectId: 'proj_atlas',
    name: '增长实验组',
    status: 'ACTIVE',
    rolesCount: 2,
    queuedTasksCount: 2,
    revision: 9,
    purpose: '增长实验的界面与验证，独立于核心链路',
    policyRevision: 1,
    activeRunsCount: 0,
    needsUserCount: 1,
  },
  {
    id: 'sp_site',
    projectId: 'proj_nova',
    name: '站点组',
    status: 'ACTIVE',
    rolesCount: 1,
    queuedTasksCount: 0,
    revision: 5,
    purpose: '官网内容与发布',
    policyRevision: 1,
    activeRunsCount: 0,
    needsUserCount: 0,
  },
];

export const roles: RoleVM[] = [
  {
    id: 'role_lin',
    spaceId: 'sp_core',
    name: '林岚',
    description: '支付链路的规划与拆分，产出可执行任务',
    status: 'ACTIVE',
    harness: 'codex',
    harnessSupport: 'PROBED',
    modelLabel: 'GPT-5 Codex · 高',
    workspaceLabel: '⧉ wt-core',
    queuedTasksCount: 0,
    unreadNoticesCount: 0,
    pendingApprovalsCount: 0,
    revision: 22,
    charterRevision: 2,
    bootstrapState: 'DELIVERED',
  },
  {
    id: 'role_zhou',
    spaceId: 'sp_core',
    name: '周实现',
    description: '核心链路的代码实现，结果交给复核',
    status: 'ACTIVE',
    harness: 'codex',
    harnessSupport: 'PROBED',
    modelLabel: 'GPT-5 Codex · 高',
    workspaceLabel: '⧉ wt-core',
    taskState: 'ACTIVE',
    runState: 'SETTLING',
    currentTaskSummary: '实现退款接口的幂等改造',
    queuedTasksCount: 0,
    unreadNoticesCount: 1,
    pendingApprovalsCount: 0,
    revision: 30,
    charterRevision: 2,
    bootstrapState: 'DELIVERED',
  },
  {
    id: 'role_chen',
    spaceId: 'sp_core',
    name: '陈复核',
    description: '复核实现结果，决定是否交付用户',
    status: 'ACTIVE',
    harness: 'pi',
    harnessSupport: 'PROBED',
    modelLabel: 'pi-pro · 中',
    workspaceLabel: '⧉ wt-core',
    taskState: 'ACTIVE',
    runState: 'WAITING_APPROVAL',
    currentTaskSummary: '复核退款幂等改造',
    queuedTasksCount: 0,
    unreadNoticesCount: 0,
    pendingApprovalsCount: 1,
    revision: 17,
    charterRevision: 1,
    bootstrapState: 'DELIVERED',
  },
  {
    id: 'role_su',
    spaceId: 'sp_growth',
    name: '苏界面',
    description: '增长实验的界面实现',
    status: 'ACTIVE',
    harness: 'kimi_code',
    harnessSupport: 'UNAVAILABLE',
    modelLabel: 'K2 · 标准',
    workspaceLabel: '⧉ wt-growth',
    taskState: 'NEEDS_ATTENTION',
    runState: 'UNKNOWN',
    currentTaskSummary: '实验位banner联调',
    queuedTasksCount: 0,
    unreadNoticesCount: 0,
    pendingApprovalsCount: 0,
    revision: 11,
    charterRevision: 1,
    bootstrapState: 'DELIVERED',
  },
  {
    id: 'role_tang',
    spaceId: 'sp_growth',
    name: '唐测试',
    description: '增长实验的验证与回归',
    status: 'PAUSED',
    harness: 'pi',
    harnessSupport: 'PROBED',
    modelLabel: 'pi-pro · 中',
    workspaceLabel: '⧉ wt-growth',
    queuedTasksCount: 2,
    unreadNoticesCount: 0,
    pendingApprovalsCount: 0,
    revision: 8,
    charterRevision: 1,
    bootstrapState: 'DELIVERED',
  },
  {
    id: 'role_he',
    spaceId: 'sp_site',
    name: '何文档',
    description: '官网内容撰写与发布',
    status: 'ACTIVE',
    harness: 'codex',
    harnessSupport: 'PROBED',
    modelLabel: 'GPT-5 Codex · 中',
    workspaceLabel: '主目录',
    queuedTasksCount: 0,
    unreadNoticesCount: 0,
    pendingApprovalsCount: 0,
    revision: 6,
    charterRevision: 1,
    bootstrapState: 'DELIVERED',
  },
];

export const tasks: TaskVM[] = [
  {
    id: 'task_refund',
    spaceId: 'sp_core',
    requesterRoleId: 'role_lin',
    assigneeRoleId: 'role_zhou',
    summary: '实现退款接口的幂等改造',
    state: 'ACTIVE',
    acceptance: 'PENDING',
    completionTargetLabel: '陈复核',
    createdAtMs: FIXED_NOW - 3 * H,
    updatedAtMs: FIXED_NOW - 20 * M,
    revision: 9,
  },
  {
    id: 'task_review',
    spaceId: 'sp_core',
    requesterRoleId: 'role_zhou',
    assigneeRoleId: 'role_chen',
    summary: '复核退款幂等改造',
    state: 'ACTIVE',
    acceptance: 'PENDING',
    completionTargetLabel: '用户',
    createdAtMs: FIXED_NOW - 90 * M,
    updatedAtMs: FIXED_NOW - 12 * M,
    revision: 4,
    sourceTaskId: 'task_refund',
  },
  {
    id: 'task_banner',
    spaceId: 'sp_growth',
    assigneeRoleId: 'role_su',
    summary: '实验位 banner 联调',
    state: 'NEEDS_ATTENTION',
    acceptance: 'PENDING',
    completionTargetLabel: '用户',
    createdAtMs: FIXED_NOW - 26 * H,
    updatedAtMs: FIXED_NOW - 2 * H,
    blockedReason: 'Run 状态未知，需要对账',
    revision: 7,
  },
  {
    id: 'task_regress_a',
    spaceId: 'sp_growth',
    assigneeRoleId: 'role_tang',
    summary: '回归：支付成功页实验分组',
    state: 'QUEUED',
    acceptance: 'PENDING',
    completionTargetLabel: '用户',
    createdAtMs: FIXED_NOW - 5 * H,
    updatedAtMs: FIXED_NOW - 5 * H,
    queuePosition: 1,
    revision: 2,
  },
  {
    id: 'task_regress_b',
    spaceId: 'sp_growth',
    assigneeRoleId: 'role_tang',
    summary: '回归：优惠券入口实验',
    state: 'QUEUED',
    acceptance: 'PENDING',
    completionTargetLabel: '用户',
    createdAtMs: FIXED_NOW - 4 * H,
    updatedAtMs: FIXED_NOW - 4 * H,
    queuePosition: 2,
    revision: 2,
  },
];

export const runs: RunVM[] = [
  {
    id: 'run_412',
    roleId: 'role_zhou',
    taskId: 'task_refund',
    harness: 'codex',
    state: 'SETTLING',
    startedAtMs: FIXED_NOW - 80 * M,
    nativeSessionDisplay: 'codex session a1b2',
    reconciliationRequired: false,
    revision: 14,
  },
  {
    id: 'run_413',
    roleId: 'role_chen',
    taskId: 'task_review',
    harness: 'pi',
    state: 'WAITING_APPROVAL',
    startedAtMs: FIXED_NOW - 40 * M,
    nativeSessionDisplay: 'pi session c3d4',
    reconciliationRequired: false,
    revision: 6,
  },
  {
    id: 'run_390',
    roleId: 'role_su',
    taskId: 'task_banner',
    harness: 'kimi_code',
    state: 'UNKNOWN',
    startedAtMs: FIXED_NOW - 26 * H,
    nativeSessionDisplay: 'kimi session e5f6',
    exitReason: '与原生会话失联',
    reconciliationRequired: true,
    revision: 3,
  },
  {
    id: 'run_388',
    roleId: 'role_lin',
    harness: 'codex',
    state: 'SUCCEEDED',
    startedAtMs: FIXED_NOW - 30 * H,
    settledAtMs: FIXED_NOW - 29 * H,
    reconciliationRequired: false,
    revision: 5,
  },
];

export const approvals: ApprovalVM[] = [
  {
    id: 'apv_01',
    runId: 'run_413',
    state: 'PENDING',
    title: '允许访问支付网关沙箱配置',
    riskLevel: 'HIGH',
    requestedAtMs: FIXED_NOW - 12 * M,
    expiresAtMs: FIXED_NOW + 48 * M,
    revision: 1,
  },
];

export const issues: IssueVM[] = [
  {
    id: 'iss_01',
    code: 'RUN_UNKNOWN',
    state: 'OPEN',
    projectId: 'proj_atlas',
    spaceId: 'sp_growth',
    roleId: 'role_su',
    taskId: 'task_banner',
    runId: 'run_390',
    messageKey: 'issue.run_unknown',
    createdAtMs: FIXED_NOW - 2 * H,
    revision: 1,
  },
];

export const results: ResultVM[] = [
  {
    id: 'res_01',
    taskId: 'task_review',
    summary: '退款幂等改造复核通过，建议合并前补充一笔沙箱回归',
    acceptance: 'PENDING',
    delivery: 'DELIVERED',
    artifactIds: ['art_diff', 'art_report'],
    revision: 2,
  },
];

export const workspaces: WorkspaceVM[] = [
  {
    id: 'ws_core',
    projectId: 'proj_atlas',
    label: 'wt-core',
    kind: 'WORKTREE',
    displayPath: '~/work/pay-core/.worktrees/wt-core',
    status: 'READY',
    access: 'SERIAL_WRITE',
    branchLabel: 'feat/refund-idempotent',
    baseCommit: '9f31ac2',
    revision: 4,
  },
  {
    id: 'ws_growth',
    projectId: 'proj_atlas',
    label: 'wt-growth',
    kind: 'WORKTREE',
    displayPath: '~/work/pay-core/.worktrees/wt-growth',
    status: 'READY',
    access: 'SERIAL_WRITE',
    branchLabel: 'feat/growth-banner',
    baseCommit: '9f31ac2',
    revision: 2,
  },
  {
    id: 'ws_nova',
    projectId: 'proj_nova',
    label: '主目录',
    kind: 'DIRECTORY',
    displayPath: 'D:\\sites\\nova-web',
    status: 'READY',
    access: 'SERIAL_WRITE',
    revision: 1,
  },
];

export const providerProfiles: ProviderProfileVM[] = [
  {
    id: 'pp_codex_main',
    providerId: 'openai',
    label: 'Codex 主账号',
    harness: 'codex',
    status: 'READY',
    mock: false,
  },
  {
    id: 'pp_pi_main',
    providerId: 'pi',
    label: 'pi 主账号',
    harness: 'pi',
    status: 'REQUIRES_LOGIN',
    mock: false,
  },
  {
    id: 'pp_kimi_main',
    providerId: 'moonshot',
    label: 'Kimi 账号',
    harness: 'kimi_code',
    status: 'UNVERIFIED',
    mock: false,
  },
];

export const modelCatalog: ModelDescriptorVM[] = [
  {
    id: 'mdl_gpt5_codex',
    harness: 'codex',
    provider_id: 'openai',
    provider_profile_id: 'pp_codex_main',
    model_id: 'gpt-5-codex',
    display_name: 'GPT-5 Codex',
    source: 'RUNTIME',
    availability: 'AVAILABLE',
    modalities: ['text'],
    tool_support: 'SUPPORTED',
    reasoning: { control: 'reasoning_effort', levels: ['低', '中', '高'], default: '中' },
    last_observed_at: FIXED_NOW - 10 * M,
    compatibility_notes: [],
    context_tokens: 272000,
  },
  {
    id: 'mdl_gpt5_mini',
    harness: 'codex',
    provider_id: 'openai',
    provider_profile_id: 'pp_codex_main',
    model_id: 'gpt-5-mini',
    display_name: 'GPT-5 Mini',
    source: 'VERIFIED_CACHE',
    availability: 'UNVERIFIED',
    modalities: ['text'],
    tool_support: 'VERIFY_AT_RUNTIME',
    reasoning: { control: 'reasoning_effort', levels: ['低', '中'], default: '低' },
    last_observed_at: FIXED_NOW - 72 * H,
    compatibility_notes: ['上次验证距今超过 72 小时'],
  },
  {
    id: 'mdl_pi_pro',
    harness: 'pi',
    provider_id: 'pi',
    provider_profile_id: 'pp_pi_main',
    model_id: 'pi-pro',
    display_name: 'pi-pro',
    source: 'SEED',
    availability: 'REQUIRES_LOGIN',
    modalities: ['text'],
    tool_support: 'VERIFY_AT_RUNTIME',
    reasoning: { control: 'reasoning_effort', levels: ['低', '中', '高'], default: '中' },
    compatibility_notes: ['种子目录，需登录后验证'],
  },
  {
    id: 'mdl_k2',
    harness: 'kimi_code',
    provider_id: 'moonshot',
    provider_profile_id: 'pp_kimi_main',
    model_id: 'k2',
    display_name: 'K2',
    source: 'SEED',
    availability: 'UNVERIFIED',
    modalities: ['text'],
    tool_support: 'VERIFY_AT_RUNTIME',
    reasoning: { control: 'none', levels: [] },
    compatibility_notes: ['种子目录，未验证'],
  },
];

export const accountProfiles: AccountProfileVM[] = [
  {
    id: 'pp_codex_main',
    harness: 'codex',
    label: 'Codex 主账号',
    maskedIdentity: 'l***e@example.com',
    status: 'READY',
    quotaStatus: 'OK',
    revision: 3,
  },
  {
    id: 'pp_pi_main',
    harness: 'pi',
    label: 'pi 主账号',
    maskedIdentity: 'p***i@example.com',
    status: 'UNKNOWN',
    quotaStatus: 'UNKNOWN',
    revision: 2,
  },
  {
    id: 'pp_kimi_main',
    harness: 'kimi_code',
    label: 'Kimi 账号',
    status: 'EXPIRED',
    quotaStatus: 'STALE',
    revision: 1,
  },
];

export const quotas: QuotaVM[] = [
  { profileId: 'pp_codex_main', status: 'OK', observedAtMs: FIXED_NOW - 15 * M, remainingPercent: 62 },
  { profileId: 'pp_pi_main', status: 'UNKNOWN', observedAtMs: FIXED_NOW - 26 * H, remainingPercent: null },
  { profileId: 'pp_kimi_main', status: 'STALE', observedAtMs: FIXED_NOW - 96 * H, remainingPercent: 18 },
];

export const artifacts: ArtifactVM[] = [
  {
    id: 'art_diff',
    mediaType: 'text/x-diff',
    byteSize: 18432,
    sha256: 'f'.repeat(64),
    state: 'AVAILABLE',
    displaySource: 'run_413 · refund-idempotent.diff',
    createdAtMs: FIXED_NOW - 30 * M,
    revision: 1,
  },
  {
    id: 'art_report',
    mediaType: 'text/markdown',
    byteSize: 4096,
    sha256: 'a'.repeat(64),
    state: 'AVAILABLE',
    displaySource: 'run_413 · review-report.md',
    createdAtMs: FIXED_NOW - 28 * M,
    revision: 1,
  },
];

export const conversation: ConversationItemVM[] = [
  {
    id: 'cv_01',
    cursor: 101,
    kind: 'SYSTEM_EVENT',
    roleId: 'role_zhou',
    occurredAtMs: FIXED_NOW - 30 * H,
    title: 'Role Charter 已生效（r2）',
    body: '使命：核心链路的代码实现，结果交给复核。\nBootstrap 已完成，角色可接收任务。',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_02',
    cursor: 102,
    kind: 'ROUTE_TASK',
    roleId: 'role_zhou',
    taskId: 'task_refund',
    occurredAtMs: FIXED_NOW - 3 * H,
    title: '来自 林岚 的任务',
    body: '实现退款接口的幂等改造。完成定义：重复请求不产生重复退款。',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_03',
    cursor: 103,
    kind: 'ASSISTANT_MESSAGE',
    roleId: 'role_zhou',
    runId: 'run_412',
    taskId: 'task_refund',
    occurredAtMs: FIXED_NOW - 78 * M,
    body: '先读取退款处理器与现有幂等键设计，确认改造点。',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_04',
    cursor: 104,
    kind: 'TOOL_CALL',
    roleId: 'role_zhou',
    runId: 'run_412',
    occurredAtMs: FIXED_NOW - 70 * M,
    title: 'apply_patch',
    body: 'refund/handler.ts：引入 idempotency_key 去重表',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_05',
    cursor: 105,
    kind: 'TOOL_RESULT',
    roleId: 'role_zhou',
    runId: 'run_412',
    occurredAtMs: FIXED_NOW - 69 * M,
    title: 'apply_patch 完成',
    state: 'ok',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_06',
    cursor: 106,
    kind: 'USER_MESSAGE',
    roleId: 'role_zhou',
    occurredAtMs: FIXED_NOW - 50 * M,
    body: '注意保持与现有对账任务的兼容。',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_07',
    cursor: 107,
    kind: 'ROUTE_RESULT',
    roleId: 'role_zhou',
    taskId: 'task_refund',
    occurredAtMs: FIXED_NOW - 20 * M,
    title: '结果已转交 陈复核',
    body: '实现完成，进入复核。',
    replay: false,
    sensitive: false,
  },
  {
    id: 'cv_08',
    cursor: 108,
    kind: 'GAP',
    roleId: 'role_zhou',
    occurredAtMs: FIXED_NOW - 45 * M,
    title: '对话存在缺口',
    body: '12:40–12:44 之间的事件流中断，已按游标重新拉取。',
    replay: true,
    sensitive: false,
  },
];

export function charterFor(role: RoleVM): RoleCharterVM {
  const space = spaces.find((s) => s.id === role.spaceId)!;
  const ws = workspaces.find((w) => role.workspaceLabel.includes(w.label)) ?? workspaces[0];
  const mates = roles
    .filter((r) => r.spaceId === role.spaceId && r.id !== role.id)
    .map((r) => ({ roleId: r.id, displayName: r.name }));
  return {
    id: `charter_${role.id}`,
    roleId: role.id,
    projectId: space.projectId,
    spaceId: space.id,
    displayName: role.name,
    revision: role.charterRevision ?? 1,
    hash: 'h' + role.id,
    effectiveAtMs: FIXED_NOW - 30 * H,
    policyRevision: space.policyRevision ?? 1,
    workspaceId: ws.id,
    spec: {
      role_key: role.id,
      group_key: space.id,
      display_name: role.name,
      role_kind: 'specialist',
      mission: role.description,
      responsibilities: [role.description, '遵守组内完成定义与交接要求'],
      out_of_scope: ['不直接修改其他组的工作区', '不自行扩大权限'],
      accepted_inputs: ['组内任务', '用户直接输入', '关联任务的续办结果'],
      required_outputs: ['结果摘要', '必要产物'],
      default_completion_target:
        role.id === 'role_zhou'
          ? { type: 'role_key', role_key: 'role_chen' }
          : { type: 'user' },
      problem_target: { type: 'user' },
      workspace_ref: ws.label,
      requested_permissions: {
        workspace_access: 'read_write',
        allowed_paths: [ws.displayPath],
        tool_profiles: ['shell', 'apply_patch'],
        network_profile: 'provider_only',
      },
      runtime: {
        harness: role.harness,
        provider_profile_id: 'pp_codex_main',
        model_id: 'gpt-5-codex',
        reasoning_effort: '中',
        selection_source: 'runtime',
      },
      bootstrap_notes: '',
    },
    effectivePermissions: {
      workspace_access: 'read_write',
      allowed_paths: [ws.displayPath],
      tool_profiles: ['shell', 'apply_patch'],
      network_profile: 'provider_only',
      notes: '由 Core 与用户共同确认，可能与请求不同',
    },
    directory: mates,
    bootstrapState: role.bootstrapState ?? 'PENDING',
    bindingEpoch: 1,
  };
}

/** 演示用 Role Plan：双组三角色（与 fixtures/client-c1r1/two-groups.plan.json 同形态）。 */
export const samplePlan: RolePlanInput = {
  schema_version: 'agentrouter-role-plan/1',
  project_id: 'proj_atlas',
  title: '清结算增强：双组编排',
  source: 'external_ai',
  goals: ['新增清结算增强链路', '与核心链路组隔离'],
  non_goals: ['不改动现有退款链路'],
  assumptions: ['核心链路组保持现状'],
  groups: [
    {
      group_key: 'g_settle',
      display_name: '清结算组',
      purpose: '清结算增强链路的实现与验证',
      communication_boundary: 'within_group_only',
      workspace_strategy: 'dedicated_worktree',
      rules: {
        handoff_requirements: ['实现完成必须交复核'],
        completion_definition: ['沙箱回归通过'],
        parallelism_notes: '组内串行写',
      },
    },
  ],
  roles: [
    {
      role_key: 'r_settle_dev',
      group_key: 'g_settle',
      display_name: '郑结算',
      role_kind: 'executor',
      mission: '实现清结算增强链路',
      responsibilities: ['清结算增强的代码实现'],
      out_of_scope: ['不改动退款链路'],
      accepted_inputs: ['组内任务'],
      required_outputs: ['结果摘要', '变更 diff'],
      default_completion_target: { type: 'role_key', role_key: 'r_settle_review' },
      problem_target: { type: 'user' },
      workspace_ref: 'wt-settle',
      requested_permissions: {
        workspace_access: 'read_write',
        allowed_paths: ['~/work/pay-core/.worktrees/wt-settle'],
        tool_profiles: ['shell', 'apply_patch'],
        network_profile: 'custom_request',
        notes: '需要访问清结算沙箱',
      },
      runtime: {
        harness: 'codex',
        provider_profile_id: 'pp_codex_main',
        model_id: 'gpt-5-codex',
        reasoning_effort: '高',
        selection_source: 'runtime',
      },
      bootstrap_notes: '先读清结算现有设计文档',
    },
    {
      role_key: 'r_settle_review',
      group_key: 'g_settle',
      display_name: '王清复',
      role_kind: 'reviewer',
      mission: '复核清结算增强实现',
      responsibilities: ['复核并决定是否交付用户'],
      out_of_scope: ['不直接改实现'],
      accepted_inputs: ['组内复核任务'],
      required_outputs: ['复核结论'],
      default_completion_target: { type: 'user' },
      problem_target: { type: 'user' },
      workspace_ref: 'wt-settle',
      requested_permissions: {
        workspace_access: 'read_only',
        allowed_paths: ['~/work/pay-core/.worktrees/wt-settle'],
        tool_profiles: ['shell'],
        network_profile: 'provider_only',
      },
      runtime: {
        harness: 'pi',
        provider_profile_id: 'pp_pi_main',
        model_id: 'pi-pro',
        reasoning_effort: '中',
        selection_source: 'seed',
      },
      bootstrap_notes: '',
    },
  ],
  review: {
    requires_user_confirmation: true,
    known_risks: ['郑结算请求了自定义网络权限（custom_request）', '王清复的模型来自种子目录，未验证'],
  },
};

export const reconfigPreview: SpaceReconfigurationPreviewVM = {
  planId: 'rcfg_01',
  planHash: 'rcfg-hash-01',
  expectedRevision: 9,
  blockers: [
    { code: 'RUN_UNKNOWN', field: 'role_su / run_390' },
    { code: 'ACCOUNT_SWITCH_IN_PROGRESS', field: 'pp_kimi_main' },
  ],
  affectedRoleIds: ['role_su', 'role_tang'],
  affectedTaskIds: ['task_banner', 'task_regress_a', 'task_regress_b'],
  affectedRunIds: ['run_390'],
  affectedWorkspaceIds: ['ws_growth'],
  proposedDestinations: {
    mode: 'MERGE',
    source_space_ids: ['sp_growth', 'sp_core'],
    targets: [
      {
        group_key: 'g_merged',
        display_name: '支付平台组',
        purpose: '合并后的支付平台统一协作组',
        rules: {
          handoff_requirements: ['实现完成必须交复核'],
          completion_definition: ['沙箱回归通过'],
          parallelism_notes: '组内串行写',
        },
      },
    ],
    assignments: [],
    task_dispositions: [],
  },
  requiredConfirmations: ['合并后原组将归档，不可在 UI 内一键撤销'],
};
