import {_electron as electron,expect} from '@playwright/test';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {startCore,until} from '../w11-process-support.ts';
mkdirSync('.local/j2-tests',{recursive:true});mkdirSync('evidence/J2/screenshots',{recursive:true});
const gui=mkdtempSync(resolve('.local/j2-tests/gui-')),data=resolve(gui,'core'),projectPath=resolve(gui,'手工协作项目');mkdirSync(data);mkdirSync(projectPath);
let core!:Awaited<ReturnType<typeof startCore>>,app:any,page:any;
const checks:Array<{id:string;status:string}>=[],screenshots:any[]=[],errors:string[]=[];
const pass=(id:string)=>{checks.push({id,status:'PASS'});console.log(id);};
async function shot(name:string){const path=`evidence/J2/screenshots/LOCAL_CORE-1440x900-100-${name}.png`;await page.screenshot({path,fullPage:true,scale:'css'});screenshots.push({path,mode:'LOCAL_CORE',viewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio})),zoom:await app.evaluate(({BrowserWindow}:any)=>BrowserWindow.getAllWindows()[0].webContents.getZoomFactor())});}
try{
 core=await startCore(data);
 await core.session.request('control.release',{lease_id:core.lease.leaseId},{operationId:'op_j2_release',expectedRevision:(await core.session.request('system.snapshot',{})).revision,scope:{}});
 app=await electron.launch({executablePath:resolve('node_modules/electron/dist/electron.exe'),args:[resolve('.local/desktop-w11/p1-main.mjs')],env:{SystemRoot:process.env.SystemRoot!,WINDIR:process.env.WINDIR!,PATH:process.env.PATH!,TEMP:gui,TMP:gui,AGENTROUTER_DATA:gui,AGENTROUTER_MODE:'LOCAL_CORE'}});
 page=await app.firstWindow();page.on('pageerror',(e:Error)=>errors.push(e.message));
 await app.evaluate(({BrowserWindow}:any)=>{const win=BrowserWindow.getAllWindows()[0];win.setContentSize(1440,900);win.webContents.setZoomFactor(1);});
 await expect(page.getByRole('heading',{name:'项目',exact:true})).toBeVisible();await shot('empty-home');
 await page.getByRole('button',{name:'申请控制'}).click();
 await app.evaluate(({dialog}:any,path:string)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]});},projectPath);
 await page.getByRole('button',{name:'选择目录…'}).click();
 await expect(page.locator('[data-page="project"]')).toBeVisible();
 const project=(await core.session.request('system.snapshot',{})).projects[0];
 await page.getByRole('button',{name:/编排角色|添加角色/}).first().click();
 await page.getByRole('button',{name:'新建空白方案'}).click();
 await expect(page.getByRole('button',{name:'校验并审阅'})).toBeDisabled();
 await page.getByRole('button',{name:'为小组 1 添加角色'}).click();
 await page.getByLabel('角色 1 名称',{exact:true}).fill('资料分析');
 await page.getByRole('button',{name:'为小组 1 添加角色'}).click();
 await page.getByLabel('角色 2 名称',{exact:true}).fill('实现复核');
 await page.getByRole('button',{name:'添加小组',exact:true}).click();
 await page.getByLabel('小组 2 名称',{exact:true}).fill('独立研究');
 await page.getByRole('button',{name:'为小组 2 添加角色'}).click();
 await page.getByLabel('角色 3 名称',{exact:true}).fill('证据检查');
 await shot('manual-editor');
 await page.getByRole('button',{name:'校验并审阅'}).click();
 await expect(page.locator('[data-stage="review"]')).toBeVisible();
 await expect(page.getByText('服务器校验通过',{exact:false})).toBeVisible();
 await shot('review');
 await page.getByRole('button',{name:'返回编辑',exact:true}).click();
 await page.getByLabel('角色 1 职责',{exact:true}).fill('读取资料、核对来源并给出证据充分的结论');
 await expect(page.locator('[data-stage="review"]')).toHaveCount(0);
 await page.getByRole('button',{name:'校验并审阅'}).click();
 await expect(page.locator('[data-stage="review"]')).toBeVisible();
 for(const input of await page.locator('.confirm-row input').all())await input.check();
 await page.getByRole('button',{name:'确认并应用',exact:true}).click();
 await expect(page.locator('[data-stage="applied"]')).toBeVisible();
 let snap=await core.session.request('system.snapshot',{});expect(snap.spaces).toHaveLength(2);expect(snap.roles).toHaveLength(3);expect(snap.roles.every(r=>r.bootstrapState==='PENDING')).toBe(true);expect(snap.runs).toHaveLength(0);
 pass('J2_MANUAL_TWO_GROUPS_THREE_ROLES_ATOMIC');
 await page.getByRole('button',{name:'返回项目',exact:true}).click();await shot('two-groups');
 await page.reload();await expect(page.locator('[data-page="project"]')).toBeVisible();
 snap=await core.session.request('system.snapshot',{});expect(snap.roles).toHaveLength(3);expect(snap.runs).toHaveLength(0);pass('J2_RELOAD_SAVED_UNVERIFIED_NOT_STARTED');
 await page.getByRole('button',{name:'申请控制'}).click();
 await page.getByRole('button',{name:/编排角色|添加角色/}).first().click();
 await page.getByLabel('添加到现有小组',{exact:true}).selectOption(snap.spaces.find(g=>g.name==='小组 1')!.id);
 await expect(page.locator('[data-stage="draft"]')).toBeVisible();
 await page.getByRole('button',{name:'为小组 1 添加角色'}).click();
 await page.getByLabel('角色 1 名称',{exact:true}).fill('补充分析');
 await page.getByRole('button',{name:'校验并审阅'}).click();await expect(page.locator('[data-stage="review"]')).toBeVisible();
 for(const input of await page.locator('.confirm-row input').all())await input.check();
 await page.getByRole('button',{name:'确认并应用',exact:true}).click();await expect(page.locator('[data-stage="applied"]')).toBeVisible();
 expect((await core.session.request('system.snapshot',{})).roles).toHaveLength(4);pass('J2_ADD_EXISTING_GROUP_ROLE');
 await page.getByRole('button',{name:'返回项目',exact:true}).click();await page.getByRole('button',{name:/编排角色|添加角色/}).first().click();
 const imported=structuredClone((await core.session.request('rolePlan.list',{project_id:project.id})).items[0].sourcePlan);
 imported.project_id='external_project';for(const g of imported.groups){g.workspace_ref='external_workspace';g.display_name='导入'+g.display_name;}for(const r of imported.roles)r.workspace_ref='external_workspace';
 await page.getByLabel('粘贴协作方案 JSON').fill(JSON.stringify(imported));await page.getByRole('button',{name:'校验粘贴方案'}).click();
 await expect(page.locator('[data-stage="mapping"]')).toBeVisible();await expect(page.getByRole('button',{name:'确认映射并校验'})).toBeDisabled();
 await page.getByLabel('映射工作区 external_workspace',{exact:true}).selectOption((await core.session.request('workspace.list',{project_id:project.id})).items[0].id);
 await page.getByLabel('我确认项目与工作区映射').check();await page.getByRole('button',{name:'确认映射并校验'}).click();await expect(page.locator('[data-stage="review"]')).toBeVisible();
 for(const input of await page.locator('.confirm-row input').all())await input.check();
 await page.getByRole('button',{name:'确认并应用',exact:true}).click();await expect(page.locator('[data-stage="applied"]')).toBeVisible();
 expect((await core.session.request('system.snapshot',{})).roles).toHaveLength(7);pass('J2_IMPORT_EXPLICIT_PROJECT_WORKSPACE_MAPPING');
 await page.getByRole('button',{name:'返回项目',exact:true}).click();

 const all=await core.session.request('system.snapshot',{}),originalSpace=snap.spaces.find(g=>g.name==='小组 1')!.id,a=all.roles.find(r=>r.name==='资料分析'&&r.spaceId===originalSpace)!,b=all.roles.find(r=>r.name==='实现复核'&&r.spaceId===originalSpace)!,c=all.roles.find(r=>r.name==='补充分析'&&r.spaceId===originalSpace)!;
 const finish={tool:'finish',payload:{outcome:'succeeded',summary:'核验成果',body:'**隔离执行证据**，不是真实模型。',outputs:[]}};
 await core.control('configureFixture',{roleId:a.id,scenario:{steps:[{tool:'wait',payload:{waiting_for:'user_input',reason:'请明确核验范围'}}],continuationSteps:[finish]}});
 for(const role of [b,c])await core.control('configureFixture',{roleId:role.id,scenario:{steps:[finish],delayMs:1200}});
 for(const role of [a,b,c])await until(()=>core.session.request('roleCharter.get',{project_id:project.id,role_id:role.id}),v=>v.bootstrapState==='DELIVERED');
 await page.locator(`a[href="#/role/${a.id}"]`).first().click();await expect(page.locator('[data-page="role"]')).toBeVisible();
 const body=page.getByLabel(`任务内容（去向：${a.name}）`,{exact:true});await body.fill('J2 用户补充');
 await body.dispatchEvent('compositionstart');await body.press('Control+Enter');expect((await core.control('inspect')).tasks).toHaveLength(0);await body.dispatchEvent('compositionend');await body.press('Control+Enter');
 await expect(page.locator('[data-action-state="succeeded"]').first()).toBeVisible();
 const waiting=await until(()=>core.session.request('system.snapshot',{}),v=>v.tasks.some(t=>t.assigneeRoleId===a.id&&t.blockedReason==='WAITING_FOR_USER_INPUT'));
 const original=waiting.tasks.find(t=>t.assigneeRoleId===a.id)!;
 await page.getByRole('button',{name:'补充到任务',exact:true}).click();await page.getByLabel('补充目标任务',{exact:true}).selectOption(original.id);await expect(page.getByLabel('补充目标任务',{exact:true})).toHaveValue(original.id);
 await page.getByLabel('补充内容',{exact:true}).fill('仅核验已提供的离线资料');await page.getByRole('button',{name:'新任务',exact:true}).click();await page.getByLabel(`任务内容（去向：${a.name}）`,{exact:true}).fill('下一项独立草稿');await page.getByRole('button',{name:'补充到任务',exact:true}).click();await expect(page.getByLabel('补充内容',{exact:true})).toHaveValue('仅核验已提供的离线资料');
 await page.getByRole('button',{name:'提交补充',exact:true}).click();await until(()=>core.session.request('inbox.list',{}),v=>v.items.length===1);expect((await core.control('inspect')).tasks).toHaveLength(1);pass('J2_NEW_TASK_IME_AND_BOUND_TASK_INPUT');await shot('role-conversation');
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByRole('heading',{name:b.name,exact:true})).toBeVisible();
 for(const title of ['J2 队列一','J2 队列二']){
  await page.getByLabel(`任务内容（去向：${b.name}）`,{exact:true}).fill(title);
  await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await expect(page.locator('[data-action-state="succeeded"]').first()).toBeVisible();
 }
 await until(()=>core.session.request('inbox.list',{}),v=>v.items.length===3);const fifo=await core.control('inspect');expect(fifo.tasks.filter((t:any)=>t.summary.startsWith('J2 队列')).map((t:any)=>t.summary)).toEqual(['J2 队列一','J2 队列二']);pass('J2_DOUBLE_CLICK_AND_FIFO');
 const request=(id:string,completion:any)=>({kind:'task.request',to:{type:'role',id},summary:'J2 下游工作',body:'核对上游结果并按明确要求交付',inputs:[],expected:['核验成果'],completion});
 await core.control('configureFixture',{roleId:a.id,scenario:{steps:[{...finish,payload:{...finish.payload,next_request:request(b.id,{mode:'handoff',to:{type:'role',id:c.id},instruction:'汇总并交付用户'})}}]}});
 await core.control('configureFixture',{roleId:b.id,scenario:{steps:[{...finish,payload:{...finish.payload,next_request:request(c.id,{mode:'result',to:{type:'user'}})}}],delayMs:1600,exitDelayMs:1600}});
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},a.id);await expect(page.getByRole('heading',{name:a.name,exact:true})).toBeVisible();
 await page.getByLabel(`任务内容（去向：${a.name}）`,{exact:true}).fill('J2 三角色流水线');await page.getByLabel('结果去向',{exact:true}).selectOption(b.id);await page.getByLabel('交接任务给目标角色').check();await expect(page.getByRole('button',{name:/^提交任务$|^派发到队列$/})).toBeDisabled();await page.getByLabel('下一步要求',{exact:true}).fill('复核资料并继续交给汇总角色');await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).click();
 await until(()=>core.control('inspect'),v=>v.runs.some((r:any)=>r.role_id===b.id&&r.state==='SETTLING')&&v.outbox.some((o:any)=>o.state==='HELD'));
 expect((await core.control('inspect')).runs.filter((r:any)=>r.role_id===c.id)).toHaveLength(0);
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByText('收尾中',{exact:true}).first()).toBeVisible();await shot('settling-held');
 await until(()=>core.session.request('inbox.list',{}),v=>v.items.length===4);pass('J2_EXPLICIT_HANDOFF_NATIVE_BARRIER');
 await core.control('seedHistory',{roleId:a.id,label:'A_独立资料'});await core.control('seedHistory',{roleId:b.id,label:'B_独立资料'});
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},a.id);await expect(page.getByText('A_独立资料 历史 0',{exact:true})).toBeVisible();await page.getByRole('button',{name:'加载更多记录',exact:true}).click();await expect(page.getByText('A_独立资料 历史 149',{exact:true})).toBeVisible();expect(await page.evaluate(()=>typeof (window as any).hiddenInjected)).toBe('undefined');await shot('history-150');pass('J2_HISTORY_150_MARKDOWN_SAFE');
 await core.control('historyFault',{fail:true});await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByText(/读取失败不代表没有记录/)).toBeVisible();await shot('history-read-error');await page.getByRole('button',{name:'重试读取',exact:true}).click();await expect(page.getByText('B_独立资料 历史 0',{exact:true})).toBeVisible();expect(await page.getByText('A_独立资料 历史 0',{exact:true}).count()).toBe(0);pass('J2_HISTORY_ERROR_NOT_EMPTY');
 await core.control('historyFault',{delayMs:400});await page.evaluate((id:string)=>{location.hash='#/role/'+id;},a.id);await expect(page.getByRole('heading',{name:a.name,exact:true})).toBeVisible();await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByText('B_独立资料 历史 0',{exact:true})).toBeVisible();expect(await page.getByText('A_独立资料 历史 0',{exact:true}).count()).toBe(0);await core.control('historyFault',{delayMs:0});pass('J2_FAST_ROLE_SWITCH_ISOLATED');
 const beforeCounts=await core.control('requestCounts');await core.control('burstEvents',{roleId:b.id});await expect(page.getByRole('button',{name:'加载更多记录',exact:true})).toBeVisible();await new Promise(r=>setTimeout(r,700));const afterCounts=await core.control('requestCounts');expect((afterCounts['system.snapshot']??0)-(beforeCounts['system.snapshot']??0)).toBeLessThanOrEqual(4);expect(afterCounts['conversation.read']).toBe(beforeCounts['conversation.read']);pass('J2_EVENT_REFRESH_COALESCED');
 expect(errors).toEqual([]);
}catch(e){console.error(e);console.error(await page?.locator('body').innerText().catch(()=>''));process.exitCode=1;checks.push({id:'J2_DESKTOP',status:'FAIL'});if(page)await shot('failure').catch(()=>{});}
finally{
 if(app){const child=app.process();await app.evaluate(({BrowserWindow}:any)=>BrowserWindow.getAllWindows()[0]?.close()).catch(()=>{});if(child.exitCode===null&&child.signalCode===null)await new Promise(r=>child.once('exit',r));}
 await core?.stop();writeFileSync('evidence/J2/desktop.json',JSON.stringify({mode:'REAL_ELECTRON_LOCAL_CORE',realHarnessSupport:0,nativeDialogs:'CONTROLLED_RETURN_MANUAL_NOT_RUN',checks,screenshots},null,2)+'\n');
}
