import { evidencePath } from '../evidence-path.ts';
import {_electron as electron,expect} from '@playwright/test';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const sourceDirty=execFileSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),'status','--porcelain','--','apps','packages','tests','tools','native'],{encoding:'utf8'}).trim().length>0;
const sourceSha=execFileSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),'rev-parse','HEAD'],{encoding:'utf8'}).trim();
import {startCore,until} from '../w11-process-support.ts';
mkdirSync('.local/j2-tests',{recursive:true});mkdirSync(evidencePath('J2/screenshots'),{recursive:true});
const gui=mkdtempSync(resolve('.local/j2-tests/gui-')),data=resolve(gui,'core'),projectPath=resolve(gui,'手工协作项目');mkdirSync(data);mkdirSync(projectPath);
let core!:Awaited<ReturnType<typeof startCore>>,app:any,page:any;
const checks:Array<{id:string;status:string}>=[],screenshots:any[]=[],errors:string[]=[];
const pass=(id:string)=>{checks.push({id,status:'PASS'});console.log(id);};
async function shot(name:string){const dimensions=await app.evaluate(({BrowserWindow}:any)=>{const w=BrowserWindow.getAllWindows()[0];return {size:w.getContentSize(),zoom:w.webContents.getZoomFactor()};});const path=evidencePath(`J2/screenshots/LOCAL_CORE-${dimensions.size.join('x')}-${Math.round(dimensions.zoom*100)}-${name}.png`);const capture=await app.evaluate(async({BrowserWindow}:any)=>{const image=await BrowserWindow.getAllWindows()[0].webContents.capturePage();return {png:image.toPNG().toString('base64'),size:image.getSize()};});writeFileSync(path,Buffer.from(capture.png,'base64'));screenshots.push({path,pixelSize:capture.size,sourceSha,sourceDirty,mode:'LOCAL_CORE',viewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio})),zoom:await app.evaluate(({BrowserWindow}:any)=>BrowserWindow.getAllWindows()[0].webContents.getZoomFactor())});}
try{
 core=await startCore(data);
 await core.session.request('control.release',{lease_id:core.lease.leaseId},{operationId:'op_j2_release',expectedRevision:(await core.session.request('system.snapshot',{})).revision,scope:{}});
 app=await electron.launch({executablePath:resolve('node_modules/electron/dist/electron.exe'),args:[resolve('.local/desktop-w11/p1-main.mjs')],env:{SystemRoot:process.env.SystemRoot!,WINDIR:process.env.WINDIR!,PATH:process.env.PATH!,TEMP:gui,TMP:gui,AGENTROUTER_DATA:gui,AGENTROUTER_MODE:'LOCAL_CORE'}});
 page=await app.firstWindow();page.on('pageerror',(e:Error)=>errors.push(e.message));
 await app.evaluate(({BrowserWindow}:any)=>{const win=BrowserWindow.getAllWindows()[0];win.setContentSize(1440,900);win.webContents.setZoomFactor(1);});
 await expect(page.getByRole('heading',{name:'项目',exact:true})).toBeVisible();await shot('empty-home');
 await page.getByRole('button',{name:'申请控制'}).click();
 await app.evaluate(({dialog}:any,path:string)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[path]});},projectPath);
 await page.getByRole('button',{name:'选择目录…'}).click();
 await expect(page.locator('[data-page="project"]')).toBeVisible();
 const project=(await core.session.request('system.snapshot',{})).projects[0];
 await page.getByRole('button',{name:/编排角色|新建角色/}).first().click();
 await page.getByRole('button',{name:'新建空白方案'}).click();
 await expect(page.getByRole('button',{name:'校验并审阅'})).toBeDisabled();
 await page.getByRole('button',{name:'为小组 1 添加角色'}).click();
 await page.getByLabel('角色 1 名称',{exact:true}).fill('资料分析');
 await page.getByRole('button',{name:'为小组 1 添加角色'}).click();
 await page.getByLabel('角色 2 名称',{exact:true}).fill('实现复核');
 await page.getByRole('button',{name:'添加小组',exact:true}).click();
 await page.getByLabel('小组 2 名称',{exact:true}).fill('独立研究');
 await page.getByRole('button',{name:'为小组 2 添加角色'}).click();
 await page.getByLabel('角色 3 名称',{exact:true}).fill('证据检查');
 await shot('manual-editor');
 await page.getByRole('button',{name:'校验并审阅'}).click();
 await expect(page.locator('[data-stage="review"]')).toBeVisible();
 await expect(page.getByText('服务器校验通过',{exact:false})).toBeVisible();
 await shot('review');
 await page.getByRole('button',{name:'返回编辑',exact:true}).click();
 await page.getByLabel('角色 1 职责',{exact:true}).fill('读取资料、核对来源并给出证据充分的结论');
 await expect(page.locator('[data-stage="review"]')).toHaveCount(0);
 await page.getByRole('button',{name:'校验并审阅'}).click();
 await expect(page.locator('[data-stage="review"]')).toBeVisible();
 for(const input of await page.locator('.confirm-row input').all())await input.check();
 await page.getByRole('button',{name:'确认并应用',exact:true}).click();
 await expect(page.locator('[data-stage="applied"]')).toBeVisible();
 let snap=await core.session.request('system.snapshot',{});expect(snap.spaces).toHaveLength(2);expect(snap.roles).toHaveLength(3);expect(snap.roles.every(r=>r.bootstrapState==='PENDING')).toBe(true);expect(snap.runs).toHaveLength(0);
 pass('J2_MANUAL_TWO_GROUPS_THREE_ROLES_ATOMIC');
 await page.getByRole('button',{name:'返回项目',exact:true}).click();await shot('two-groups');
 await page.reload();await expect(page.locator('[data-page="project"]')).toBeVisible();
 snap=await core.session.request('system.snapshot',{});expect(snap.roles).toHaveLength(3);expect(snap.runs).toHaveLength(0);pass('J2_RELOAD_SAVED_UNVERIFIED_NOT_STARTED');
 await page.getByRole('button',{name:'申请控制'}).click();
 await page.getByRole('button',{name:/编排角色|新建角色/}).first().click();
 await page.getByLabel('添加到现有小组',{exact:true}).selectOption(snap.spaces.find(g=>g.name==='小组 1')!.id);
 await expect(page.locator('[data-stage="draft"]')).toBeVisible();
 await page.getByRole('button',{name:'为小组 1 添加角色'}).click();
 await page.getByLabel('角色 1 名称',{exact:true}).fill('补充分析');
 await page.getByRole('button',{name:'校验并审阅'}).click();await expect(page.locator('[data-stage="review"]')).toBeVisible();
 for(const input of await page.locator('.confirm-row input').all())await input.check();
 await page.getByRole('button',{name:'确认并应用',exact:true}).click();await expect(page.locator('[data-stage="applied"]')).toBeVisible();
 expect((await core.session.request('system.snapshot',{})).roles).toHaveLength(4);pass('J2_ADD_EXISTING_GROUP_ROLE');
 await page.getByRole('button',{name:'返回项目',exact:true}).click();await page.getByRole('button',{name:/编排角色|新建角色/}).first().click();
 const imported=structuredClone((await core.session.request('rolePlan.list',{project_id:project.id})).items[0].sourcePlan);
 imported.project_id='external_project';for(const g of imported.groups){g.workspace_ref='external_workspace';g.display_name='导入'+g.display_name;}for(const r of imported.roles)r.workspace_ref='external_workspace';
 await page.getByLabel('粘贴协作方案 JSON').fill(JSON.stringify(imported));await page.getByRole('button',{name:'校验粘贴方案'}).click();
 await expect(page.locator('[data-stage="mapping"]')).toBeVisible();await expect(page.getByRole('button',{name:'确认映射并校验'})).toBeDisabled();
 await page.getByLabel('映射工作区 external_workspace',{exact:true}).selectOption((await core.session.request('workspace.list',{project_id:project.id})).items[0].id);
 await page.getByLabel('我确认项目与工作区映射').check();await page.getByRole('button',{name:'确认映射并校验'}).click();await expect(page.locator('[data-stage="review"]')).toBeVisible();
 for(const input of await page.locator('.confirm-row input').all())await input.check();
 await page.getByRole('button',{name:'确认并应用',exact:true}).click();await expect(page.locator('[data-stage="applied"]')).toBeVisible();
 expect((await core.session.request('system.snapshot',{})).roles).toHaveLength(7);pass('J2_IMPORT_EXPLICIT_PROJECT_WORKSPACE_MAPPING');
 await page.getByRole('button',{name:'返回项目',exact:true}).click();

 const all=await core.session.request('system.snapshot',{}),originalSpace=snap.spaces.find(g=>g.name==='小组 1')!.id,a=all.roles.find(r=>r.name==='资料分析'&&r.spaceId===originalSpace)!,b=all.roles.find(r=>r.name==='实现复核'&&r.spaceId===originalSpace)!,c=all.roles.find(r=>r.name==='补充分析'&&r.spaceId===originalSpace)!;
 const finish={tool:'finish',payload:{outcome:'succeeded',summary:'核验成果',body:'**隔离执行证据**，不是真实模型。',outputs:[]}};
 await core.control('configureFixture',{roleId:a.id,scenario:{steps:[{tool:'wait',payload:{waiting_for:'user_input',reason:'请明确核验范围'}}],continuationSteps:[finish]}});
 for(const role of [b,c])await core.control('configureFixture',{roleId:role.id,scenario:{steps:[finish],delayMs:1200}});
 for(const role of [a,b,c])await until(()=>core.session.request('roleCharter.get',{project_id:project.id,role_id:role.id}),v=>v.bootstrapState==='DELIVERED');
 await page.locator(`a[href="#/role/${a.id}"]`).first().click();await expect(page.locator('[data-page="role"]')).toBeVisible();
 const body=page.getByLabel(`任务内容（去向：${a.name}）`,{exact:true});await body.fill('J2 用户补充');
 await body.dispatchEvent('compositionstart');await body.press('Control+Enter');expect((await core.control('inspect')).tasks).toHaveLength(0);await body.dispatchEvent('compositionend');await body.press('Control+Enter');
 await expect(page.locator('[data-action-state="succeeded"]').first()).toBeVisible();
 const waiting=await until(()=>core.session.request('system.snapshot',{}),v=>v.tasks.some(t=>t.assigneeRoleId===a.id&&t.blockedReason==='WAITING_FOR_USER_INPUT'));
 const original=waiting.tasks.find(t=>t.assigneeRoleId===a.id)!;
 await page.getByRole('button',{name:'补充到任务',exact:true}).click();await page.getByLabel('补充目标任务',{exact:true}).selectOption(original.id);await expect(page.getByLabel('补充目标任务',{exact:true})).toHaveValue(original.id);
 await page.getByLabel('补充内容',{exact:true}).fill('仅核验已提供的离线资料');await page.getByRole('button',{name:'新任务',exact:true}).click();await page.getByLabel(`任务内容（去向：${a.name}）`,{exact:true}).fill('下一项独立草稿');await page.getByRole('button',{name:'补充到任务',exact:true}).click();await expect(page.getByLabel('补充内容',{exact:true})).toHaveValue('仅核验已提供的离线资料');
 await page.getByRole('button',{name:'提交补充',exact:true}).click();await until(()=>core.session.request('inbox.list',{}),v=>v.items.length===1);expect((await core.control('inspect')).tasks).toHaveLength(1);pass('J2_NEW_TASK_IME_AND_BOUND_TASK_INPUT');await shot('role-conversation');
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByRole('heading',{name:b.name,exact:true})).toBeVisible();
 for(const title of ['J2 队列一','J2 队列二']){
  await page.getByLabel(`任务内容（去向：${b.name}）`,{exact:true}).fill(title);
  await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).evaluate((button:HTMLButtonElement)=>{button.click();button.click();});await expect(page.locator('[data-action-state="succeeded"]').first()).toBeVisible();
 }
 await until(()=>core.session.request('inbox.list',{}),v=>v.items.length===3);const fifo=await core.control('inspect');expect(fifo.tasks.filter((t:any)=>t.summary.startsWith('J2 队列')).map((t:any)=>t.summary)).toEqual(['J2 队列一','J2 队列二']);pass('J2_DOUBLE_CLICK_AND_FIFO');
 const request=(id:string,completion:any)=>({kind:'task.request',to:{type:'role',id},summary:'J2 下游工作',body:'核对上游结果并按明确要求交付',inputs:[],expected:['核验成果'],completion});
 await core.control('configureFixture',{roleId:a.id,scenario:{steps:[{...finish,payload:{...finish.payload,next_request:request(b.id,{mode:'handoff',to:{type:'role',id:c.id},instruction:'汇总并交付用户'})}}]}});
 await core.control('configureFixture',{roleId:b.id,scenario:{steps:[{...finish,payload:{...finish.payload,next_request:request(c.id,{mode:'result',to:{type:'user'}})}}],delayMs:1600,exitDelayMs:1600}});
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},a.id);await expect(page.getByRole('heading',{name:a.name,exact:true})).toBeVisible();
 await page.getByLabel(`任务内容（去向：${a.name}）`,{exact:true}).fill('J2 三角色流水线');await page.getByLabel('结果去向',{exact:true}).selectOption(b.id);await page.getByLabel('交接任务给目标角色').check();await expect(page.getByRole('button',{name:/^提交任务$|^派发到队列$/})).toBeDisabled();await page.getByLabel('下一步要求',{exact:true}).fill('复核资料并继续交给汇总角色');await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).click();
 await until(()=>core.control('inspect'),v=>v.runs.some((r:any)=>r.role_id===b.id&&r.state==='SETTLING')&&v.outbox.some((o:any)=>o.state==='HELD'));
 expect((await core.control('inspect')).runs.filter((r:any)=>r.role_id===c.id)).toHaveLength(0);
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.locator('.role-states').getByText('收尾中',{exact:true}).first()).toBeVisible();await shot('settling-held');
 await until(()=>core.session.request('inbox.list',{}),v=>v.items.length===4);pass('J2_EXPLICIT_HANDOFF_NATIVE_BARRIER');
 await core.control('seedHistory',{roleId:a.id,label:'A_独立资料'});await core.control('seedHistory',{roleId:b.id,label:'B_独立资料'});
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},a.id);await expect(page.getByText('A_独立资料 历史 0',{exact:true})).toBeVisible();await page.getByRole('button',{name:'加载更多记录',exact:true}).click();await expect(page.getByText('A_独立资料 历史 149',{exact:true})).toBeVisible();expect(await page.evaluate(()=>typeof (window as any).hiddenInjected)).toBe('undefined');await shot('history-150');pass('J2_HISTORY_150_MARKDOWN_SAFE');
 await core.control('historyFault',{fail:true});await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByText(/读取失败不代表没有记录/)).toBeVisible();await shot('history-read-error');await page.getByRole('button',{name:'重试读取',exact:true}).click();await expect(page.getByText('B_独立资料 历史 0',{exact:true})).toBeVisible();expect(await page.getByText('A_独立资料 历史 0',{exact:true}).count()).toBe(0);pass('J2_HISTORY_ERROR_NOT_EMPTY');
 await core.control('historyFault',{delayMs:400});await page.evaluate((id:string)=>{location.hash='#/role/'+id;},a.id);await expect(page.getByRole('heading',{name:a.name,exact:true})).toBeVisible();await page.evaluate((id:string)=>{location.hash='#/role/'+id;},b.id);await expect(page.getByText('B_独立资料 历史 0',{exact:true})).toBeVisible();expect(await page.getByText('A_独立资料 历史 0',{exact:true}).count()).toBe(0);await page.getByRole('button',{name:'角色设置',exact:true}).click();const expectedCharter=await core.session.request('roleCharter.get',{project_id:project.id,role_id:b.id});await expect(page.getByTestId('charter-card')).toHaveAttribute('data-role-id',expectedCharter.roleId);await page.keyboard.press('Escape');await core.control('historyFault',{delayMs:0});pass('J2_FAST_ROLE_SWITCH_ISOLATED');
 await page.evaluate(()=>scrollTo(0,260));const oldScroll=await page.evaluate(()=>scrollY);const beforeCounts=await core.control('requestCounts');await core.control('burstEvents',{roleId:b.id});await expect(page.getByRole('button',{name:'加载更多记录',exact:true})).toBeVisible();await new Promise(r=>setTimeout(r,700));const afterCounts=await core.control('requestCounts');expect((afterCounts['system.snapshot']??0)-(beforeCounts['system.snapshot']??0)).toBeLessThanOrEqual(4);expect(afterCounts['conversation.read']).toBe(beforeCounts['conversation.read']);expect(await page.evaluate(()=>scrollY)).toBe(oldScroll);pass('J2_HISTORY_READING_ANCHOR');pass('J2_EVENT_REFRESH_COALESCED');

 await page.getByRole('button',{name:'角色设置',exact:true}).click();await expect(page.getByTestId('charter-card')).toBeVisible();await shot('role-settings');expect(await page.locator('.role-col-main').evaluate((node:HTMLElement)=>node.inert||Boolean(node.closest('[inert]')))).toBe(true);await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'角色设置',exact:true})).toBeFocused();pass('J2_SETTINGS_DRAWER_FOCUS_AND_BACKGROUND');
 await page.evaluate((id:string)=>{location.hash='#/project/'+id;},project.id);await expect(page.getByRole('tab')).toHaveCount(4);
 await page.getByRole('tab',{name:'动态',exact:true}).click();await page.getByLabel('动态角色',{exact:true}).selectOption(a.id);await expect(page.getByText('A_独立资料 历史 0',{exact:true})).toBeVisible();expect(await page.getByText('B_独立资料 历史 0',{exact:true}).count()).toBe(0);await shot('project-activity');await page.getByRole('tab',{name:/^成果/}).click();await page.getByRole('button',{name:'文件与报告'}).click();await expect(page.locator('[data-tab="artifacts"]')).toBeVisible();await page.getByRole('tab',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'运行环境'}).click();await expect(page.locator('[data-tab="models"]')).toBeVisible();await shot('runtime-settings');await page.goBack();await expect(page.locator('[data-tab="settings"]')).toBeVisible();pass('J2_FOUR_ENTRIES_FILTERS_BACK');
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},c.id);await expect(page.getByRole('heading',{name:c.name,exact:true})).toBeVisible();await page.getByLabel(`任务内容（去向：${c.name}）`,{exact:true}).fill('J2 丢失回执旧意图');await core.control('dropNextReply');await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).click();await expect(page.locator('[data-action-state="uncertain"]')).toBeVisible({timeout:15000});await page.getByLabel(`任务内容（去向：${c.name}）`,{exact:true}).fill('J2 新意图草稿');await expect(page.getByRole('region',{name:'待核对提交'})).toBeVisible();await shot('uncertain-edited-draft');const taskCount=(await core.control('inspect')).tasks.length;await page.reload();await page.getByRole('button',{name:'申请控制'}).click();expect((await core.control('inspect')).tasks.length).toBe(taskCount);await page.getByText(/查看待核对操作/).click();await page.getByRole('button',{name:'按原操作重试',exact:true}).click();await expect(page.getByRole('region',{name:'待核对提交'})).toHaveCount(0);expect((await core.control('inspect')).tasks.length).toBe(taskCount);await expect(page.getByLabel(`任务内容（去向：${c.name}）`,{exact:true})).toHaveValue('J2 新意图草稿');pass('J2_UNCERTAIN_EDIT_RELOAD_ORIGINAL_RETRY');
 await page.evaluate((id:string)=>{location.hash='#/project/'+id;},project.id);await expect(page.getByRole('tab',{name:'工作台'})).toBeVisible();
 for(const factor of [1.25,1.5,2]){await app.evaluate(({BrowserWindow}:any,z:number)=>{const w=BrowserWindow.getAllWindows()[0];w.setContentSize(1280,720);w.webContents.setZoomFactor(z);},factor);await expect(page.getByRole('button',{name:/新建角色/})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2&&document.body.scrollWidth<=innerWidth+2)).toBe(true);const action=await page.getByRole('button',{name:/新建角色/}).boundingBox();expect(action.x+action.width).toBeLessThanOrEqual(await page.evaluate(()=>innerWidth));await shot('workbench-zoom');}pass('J2_ZOOM_125_150_200');
 await app.evaluate(({BrowserWindow}:any)=>{const w=BrowserWindow.getAllWindows()[0];w.setContentSize(1440,900);w.webContents.setZoomFactor(1);});
 const contrasts=await page.evaluate(()=>{const css=getComputedStyle(document.documentElement),lum=(hex:string)=>{const n=hex.trim().replace('#','');const c=[0,2,4].map(i=>parseInt(n.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;};return ['text','text-2','text-3','ok','warning','danger','queue','active'].map(name=>{const fg=lum(css.getPropertyValue('--'+name)),bg=lum(css.getPropertyValue(name.startsWith('text')?'--bg':'--'+name+'-soft'));return {name,ratio:(Math.max(fg,bg)+.05)/(Math.min(fg,bg)+.05)};});});for(const color of contrasts)expect(color.ratio,JSON.stringify(color)).toBeGreaterThanOrEqual(4.5);writeFileSync(evidencePath('J2/contrast.json'),JSON.stringify(contrasts,null,2));pass('J2_TEXT_CONTRAST');
 await page.evaluate((id:string)=>{location.hash='#/role/'+id;},c.id);await page.getByLabel(`任务内容（去向：${c.name}）`,{exact:true}).fill('J2 删除本机副本');await core.control('dropNextReply');await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).click();await expect(page.locator('[data-action-state="uncertain"]')).toBeVisible({timeout:15000});await page.getByText(/查看待核对操作/).click();const beforeDelete=await core.control('requestCounts');await page.getByRole('button',{name:'删除本机副本（不取消远端任务）'}).click();await expect(page.getByRole('region',{name:'待核对提交'})).toHaveCount(0);const afterDelete=await core.control('requestCounts');expect(afterDelete['task.cancel']).toBe(beforeDelete['task.cancel']);expect(afterDelete['run.cancel']).toBe(beforeDelete['run.cancel']);pass('J2_DELETE_LOCAL_COPY_NO_CANCEL');
 await core.control('denyNextMutation');await page.getByLabel(`任务内容（去向：${c.name}）`,{exact:true}).fill('J2 失败应保留正文');await page.getByRole('button',{name:/^提交任务$|^派发到队列$/}).click();await expect(page.locator('[data-action-state="failed"]')).toHaveClass(/tone-danger/);await expect(page.getByLabel(`任务内容（去向：${c.name}）`,{exact:true})).toHaveValue('J2 失败应保留正文');await shot('failed-keeps-input');pass('J2_FAILURE_RED_PRESERVES_INPUT');
 await core.stop();await expect(page.getByRole('alert').filter({hasText:'与 Core 的连接已断开'})).toBeVisible({timeout:15000});await expect(page.getByRole('button',{name:/^提交任务$|^派发到队列$/})).toBeDisabled();expect(await page.getByText('Core 正常',{exact:true}).count()).toBe(0);await shot('disconnected-readonly');pass('J2_DISCONNECTED_NO_HEALTH_PROMISE');

 expect(errors).toEqual([]);
}catch(e){console.error(e);console.error(await page?.locator('body').innerText().catch(()=>''));process.exitCode=1;checks.push({id:'J2_DESKTOP',status:'FAIL'});if(page)await shot('failure').catch(()=>{});}
finally{
 if(app){const child=app.process();await app.evaluate(({BrowserWindow}:any)=>BrowserWindow.getAllWindows()[0]?.close()).catch(()=>{});if(child.exitCode===null&&child.signalCode===null)await new Promise(r=>child.once('exit',r));}
 await core?.stop();writeFileSync(evidencePath('J2/desktop.json'),JSON.stringify({sourceSha,sourceDirty,mode:'REAL_ELECTRON_LOCAL_CORE',realHarnessSupport:0,nativeDialogs:'CONTROLLED_RETURN_MANUAL_NOT_RUN',checks,screenshots},null,2)+'\n');
}
