-- W11A additive application state; 001 remains immutable.
CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE command_ledger(principal TEXT NOT NULL,client_id TEXT NOT NULL,operation_id TEXT NOT NULL,request_hash TEXT NOT NULL,response_json TEXT NOT NULL CHECK(json_valid(response_json)),committed_at_ms INTEGER NOT NULL,PRIMARY KEY(principal,client_id,operation_id));
CREATE TABLE client_events(cursor INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT REFERENCES projects(id),revision INTEGER NOT NULL,kind TEXT NOT NULL,payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),at_ms INTEGER NOT NULL);
CREATE TABLE entity_revisions(entity_id TEXT PRIMARY KEY,revision INTEGER NOT NULL,updated_at_ms INTEGER NOT NULL);
CREATE TABLE role_plans(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),plan_hash TEXT NOT NULL,source_json TEXT NOT NULL CHECK(json_valid(source_json)),role_ids_json TEXT NOT NULL,space_ids_json TEXT NOT NULL,revision INTEGER NOT NULL,applied_by TEXT NOT NULL);
CREATE TABLE space_rules(space_id TEXT NOT NULL REFERENCES spaces(id),revision INTEGER NOT NULL,group_key TEXT NOT NULL,purpose TEXT NOT NULL,rules_json TEXT NOT NULL CHECK(json_valid(rules_json)),effective_at_ms INTEGER NOT NULL,PRIMARY KEY(space_id,revision));
CREATE TABLE role_membership_history(id TEXT PRIMARY KEY,role_id TEXT NOT NULL REFERENCES roles(id),space_id TEXT NOT NULL REFERENCES spaces(id),joined_at_ms INTEGER NOT NULL,left_at_ms INTEGER);
CREATE UNIQUE INDEX one_active_membership ON role_membership_history(role_id) WHERE left_at_ms IS NULL;
CREATE TABLE role_charters(id TEXT PRIMARY KEY,role_id TEXT NOT NULL REFERENCES roles(id),project_id TEXT NOT NULL REFERENCES projects(id),space_id TEXT NOT NULL REFERENCES spaces(id),revision INTEGER NOT NULL,hash TEXT NOT NULL,policy_revision INTEGER NOT NULL,binding_epoch INTEGER NOT NULL,workspace_id TEXT NOT NULL REFERENCES workspaces(id),spec_json TEXT NOT NULL CHECK(json_valid(spec_json)),permissions_json TEXT NOT NULL CHECK(json_valid(permissions_json)),directory_json TEXT NOT NULL CHECK(json_valid(directory_json)),effective_at_ms INTEGER NOT NULL,UNIQUE(role_id,revision));
CREATE TABLE bootstrap_deliveries(id TEXT PRIMARY KEY,role_id TEXT NOT NULL REFERENCES roles(id),charter_id TEXT NOT NULL REFERENCES role_charters(id),epoch INTEGER NOT NULL,revision INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN ('PENDING','DELIVERING','DELIVERED','FAILED')),reason TEXT,updated_at_ms INTEGER NOT NULL,UNIQUE(charter_id));
CREATE TABLE initialization_attempts(id TEXT PRIMARY KEY,delivery_id TEXT NOT NULL REFERENCES bootstrap_deliveries(id),role_id TEXT NOT NULL REFERENCES roles(id),epoch INTEGER NOT NULL,charter_hash TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('STARTING','RUNNING','DELIVERED','FAILED','UNKNOWN')),source TEXT NOT NULL CHECK(source='SIMULATED'),pid INTEGER,created_at_ms INTEGER NOT NULL,completed_at_ms INTEGER);
CREATE TABLE initialization_leases(resource_key TEXT PRIMARY KEY,attempt_id TEXT NOT NULL REFERENCES initialization_attempts(id),epoch INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN ('HELD','QUARANTINED')));
CREATE TABLE model_catalog(provider_profile_id TEXT NOT NULL,model_id TEXT NOT NULL,descriptor_json TEXT NOT NULL CHECK(json_valid(descriptor_json)),PRIMARY KEY(provider_profile_id,model_id));
CREATE TABLE conversation_items(seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,project_id TEXT NOT NULL REFERENCES projects(id),space_id TEXT NOT NULL REFERENCES spaces(id),role_id TEXT REFERENCES roles(id),task_id TEXT REFERENCES tasks(id),run_id TEXT REFERENCES runs(id),kind TEXT NOT NULL,title TEXT,body TEXT,state TEXT,at_ms INTEGER NOT NULL,source_key TEXT UNIQUE);
CREATE INDEX directed_conversation ON conversation_items(role_id,seq);
CREATE TABLE execution_profiles(role_id TEXT PRIMARY KEY REFERENCES roles(id),source TEXT NOT NULL CHECK(source='SIMULATED'),scenario_json TEXT NOT NULL CHECK(json_valid(scenario_json)),verified INTEGER NOT NULL CHECK(verified IN (0,1)));
CREATE TABLE run_sources(run_id TEXT PRIMARY KEY REFERENCES runs(id),source TEXT NOT NULL CHECK(source='SIMULATED'),charter_id TEXT NOT NULL REFERENCES role_charters(id),pid INTEGER,native_terminal INTEGER NOT NULL DEFAULT 0,resources_stopped INTEGER NOT NULL DEFAULT 0);
CREATE TABLE result_handlings(result_id TEXT PRIMARY KEY REFERENCES results(id),task_id TEXT NOT NULL UNIQUE REFERENCES tasks(id));
CREATE TABLE space_reconfigurations(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),plan_hash TEXT NOT NULL,state TEXT NOT NULL,record_json TEXT NOT NULL CHECK(json_valid(record_json)),created_at_ms INTEGER NOT NULL);
CREATE TABLE application_audit(seq INTEGER PRIMARY KEY AUTOINCREMENT,project_id TEXT REFERENCES projects(id),actor TEXT NOT NULL,kind TEXT NOT NULL,detail_json TEXT NOT NULL CHECK(json_valid(detail_json)),at_ms INTEGER NOT NULL);

CREATE TABLE cancel_intents(run_id TEXT PRIMARY KEY REFERENCES runs(id),epoch INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN ('PENDING','SENT')),created_at_ms INTEGER NOT NULL);
